### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by eed3si9n** [dwijnand/sbt1fports#1]
https://developer.github.com/v3/search/#rate-limit

> The Search API has a custom rate limit. For requests using Basic Authentication, OAuth, or client ID and secret, you can make up to 30 requests per minute.

I'm working around it by putting this at line 37:

```scala
        Thread.sleep(2100)
```

**Comment by dwijnand** [comment]
Gave you commit/push rights. So change away, this is only an interim project.
